# Generated by Django 4.2.7 on 2023-11-13 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pokemon',
            old_name='sprite',
            new_name='image',
        ),
        migrations.RemoveField(
            model_name='pokemon',
            name='abilities',
        ),
        migrations.AddField(
            model_name='pokemon',
            name='abilities_count',
            field=models.IntegerField(default=0),
        ),
    ]
