# Generated by Django 4.2.7 on 2023-11-14 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0003_ability_move_type_pokemon_abilities_pokemon_moves_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pokemon',
            name='abilities',
        ),
        migrations.RemoveField(
            model_name='pokemon',
            name='moves',
        ),
        migrations.RemoveField(
            model_name='pokemon',
            name='types',
        ),
        migrations.AddField(
            model_name='ability',
            name='pokemon',
            field=models.ManyToManyField(related_name='abilities', to='pokemon.pokemon'),
        ),
        migrations.AddField(
            model_name='move',
            name='pokemon',
            field=models.ManyToManyField(related_name='moves', to='pokemon.pokemon'),
        ),
        migrations.AddField(
            model_name='type',
            name='pokemon',
            field=models.ManyToManyField(related_name='types', to='pokemon.pokemon'),
        ),
    ]
